#!/usr/bin/env npx tsx
/**
 * Smoke test: ledger append, dedup skip, daily report generation.
 *
 * Writes a fixture report under reports/.smoke-test/ so it never
 * clobbers a real collector digest at reports/YYYY-MM-DD.md.
 */

import { readFileSync, writeFileSync, mkdirSync, rmSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { execSync } from "child_process";
import { hashSummary } from "./validate-ledger.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const LEDGER_PATH = join(ROOT, "data", "seen-items.json");
const TODAY = new Date().toISOString().slice(0, 10);
const SMOKE_DIR = join(ROOT, "reports", ".smoke-test");
const REPORT_PATH = join(SMOKE_DIR, `${TODAY}.md`);

interface LedgerItem {
  id: string;
  type: string;
  url: string;
  title: string;
  summary: string;
  topics: string[];
  first_seen: string;
  last_seen: string;
  content_hash: string;
  status: string;
  scores: null;
  supersedes: null;
  duplicate_of: null;
  stars?: number;
}

interface Ledger {
  version: number;
  items: LedgerItem[];
}

const SAMPLE: LedgerItem = {
  id: "smoke-test/init-agent-fixture",
  type: "repo",
  url: "https://github.com/smoke-test/init-agent-fixture",
  title: "init-agent-fixture",
  // Test-only fixture; bypasses collector quality heuristics (stars/activity).
  summary: "Smoke test fixture repo for validating collector dedup and report flow.",
  topics: ["cursor-skills", "automation"],
  first_seen: TODAY,
  last_seen: TODAY,
  content_hash: "",
  status: "pending_review",
  scores: null,
  supersedes: null,
  duplicate_of: null,
  stars: 0,
};

SAMPLE.content_hash = hashSummary(SAMPLE.summary);

function loadLedger(): Ledger {
  return JSON.parse(readFileSync(LEDGER_PATH, "utf-8")) as Ledger;
}

function saveLedger(ledger: Ledger): void {
  writeFileSync(LEDGER_PATH, JSON.stringify(ledger, null, 2) + "\n");
}

function appendIfNew(ledger: Ledger, item: LedgerItem): boolean {
  if (ledger.items.some((i) => i.id === item.id)) return false;
  ledger.items.push(item);
  return true;
}

function writeReport(newCount: number, skipped: number): void {
  const body =
    newCount > 0
      ? `# AI Skills Daily Digest — ${TODAY}

> Smoke test run — incremental report.

## Summary

- **New items:** ${newCount}
- **Skipped duplicates:** ${skipped}
- **Queries run:** smoke-test (no GitHub search)
- **Run date:** ${TODAY}

## New Repos

| Repo | Stars | Topics | Why useful | Link |
|------|-------|--------|------------|------|
| smoke-test/init-agent-fixture | 0 | cursor-skills, automation | Smoke test fixture for collector validation | [link](https://github.com/smoke-test/init-agent-fixture) |

## Pending Review

- \`smoke-test/init-agent-fixture\` — Smoke test fixture repo for validating collector dedup and report flow.

---

*Generated by smoke-test script.*
`
      : `# AI Skills Daily Digest — ${TODAY}

> Smoke test run — deduplication confirmed.

## Summary

- **New items:** ${newCount}
- **Skipped duplicates:** ${skipped}
- **Queries run:** smoke-test (no GitHub search)
- **Run date:** ${TODAY}

No new items today — the smoke-test fixture was already in the ledger.

---

*Generated by smoke-test script.*
`;
  mkdirSync(SMOKE_DIR, { recursive: true });
  writeFileSync(REPORT_PATH, body);
}

function main(): void {
  const ledger = loadLedger();
  const before = ledger.items.length;

  const added = appendIfNew(ledger, SAMPLE);
  // Second append must always be skipped (dedup assertion, not a report stat).
  if (appendIfNew(ledger, SAMPLE)) {
    throw new Error("Smoke test failed: duplicate append was not blocked");
  }

  if (added) saveLedger(ledger);

  // Report stats mirror a real collector run: the fixture is either one new
  // item (fresh ledger) or one skipped duplicate (already collected).
  const newCount = added ? 1 : 0;
  const skipped = added ? 0 : 1;
  writeReport(newCount, skipped);

  execSync("npm run validate-ledger", { cwd: ROOT, stdio: "inherit" });

  const after = loadLedger().items.length;
  console.log(`Smoke test OK:`);
  console.log(`  - Ledger: ${before} -> ${after} items`);
  console.log(`  - First append: ${added ? "added" : "skipped (already exists)"}`);
  console.log(`  - Dedup skip: confirmed duplicate blocked`);
  console.log(`  - Report: ${REPORT_PATH}`);

  // Clean fixture report so smoke-test leaves no untracked clutter by default.
  // Set SMOKE_KEEP=1 to inspect the generated report.
  if (process.env.SMOKE_KEEP === "1") {
    console.log(`  - Kept report for inspection (SMOKE_KEEP=1)`);
  } else {
    rmSync(SMOKE_DIR, { recursive: true, force: true });
    console.log(`  - Cleaned: ${SMOKE_DIR}`);
  }
}

main();
