#!/usr/bin/env npx tsx
/**
 * Smoke test: ledger append, dedup skip, daily report generation.
 */

import { readFileSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { execSync } from "child_process";
import { hashSummary } from "./validate-ledger.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const LEDGER_PATH = join(ROOT, "data", "seen-items.json");
const TODAY = new Date().toISOString().slice(0, 10);
const REPORT_PATH = join(ROOT, "reports", `${TODAY}.md`);

interface LedgerItem {
  id: string;
  type: string;
  url: string;
  title: string;
  summary: string;
  topics: string[];
  first_seen: string;
  last_seen: string;
  content_hash: string;
  status: string;
  scores: null;
  supersedes: null;
  duplicate_of: null;
  stars?: number;
}

interface Ledger {
  version: number;
  items: LedgerItem[];
}

const SAMPLE: LedgerItem = {
  id: "smoke-test/init-agent-fixture",
  type: "repo",
  url: "https://github.com/smoke-test/init-agent-fixture",
  title: "init-agent-fixture",
  summary: "Smoke test fixture repo for validating collector dedup and report flow.",
  topics: ["cursor-skills", "automation"],
  first_seen: TODAY,
  last_seen: TODAY,
  content_hash: "",
  status: "pending_review",
  scores: null,
  supersedes: null,
  duplicate_of: null,
  stars: 0,
};

SAMPLE.content_hash = hashSummary(SAMPLE.summary);

function loadLedger(): Ledger {
  return JSON.parse(readFileSync(LEDGER_PATH, "utf-8")) as Ledger;
}

function saveLedger(ledger: Ledger): void {
  writeFileSync(LEDGER_PATH, JSON.stringify(ledger, null, 2) + "\n");
}

function appendIfNew(ledger: Ledger, item: LedgerItem): boolean {
  if (ledger.items.some((i) => i.id === item.id)) return false;
  ledger.items.push(item);
  return true;
}

function writeReport(newCount: number, skipped: number, added: boolean): void {
  const body = added
    ? `# AI Skills Daily Digest — ${TODAY}

> Smoke test run — incremental report.

## Summary

- **New items:** 1
- **Skipped duplicates:** 0
- **Queries run:** smoke-test (no GitHub search)
- **Run date:** ${TODAY}

## New Repos

| Repo | Stars | Topics | Why useful | Link |
|------|-------|--------|------------|------|
| smoke-test/init-agent-fixture | 0 | cursor-skills, automation | Smoke test fixture for collector validation | [link](https://github.com/smoke-test/init-agent-fixture) |

## Pending Review

- \`smoke-test/init-agent-fixture\` — Smoke test fixture repo for validating collector dedup and report flow.

---

*Generated by smoke-test script.*
`
    : `# AI Skills Daily Digest — ${TODAY}

> Smoke test run — deduplication confirmed.

## Summary

- **New items:** 0
- **Skipped duplicates:** 1
- **Queries run:** smoke-test (no GitHub search)
- **Run date:** ${TODAY}

No new items today — the smoke-test fixture was already in the ledger.

---

*Generated by smoke-test script.*
`;
  writeFileSync(REPORT_PATH, body);
}

function main(): void {
  const ledger = loadLedger();
  const before = ledger.items.length;

  const added = appendIfNew(ledger, SAMPLE);
  const skipped = appendIfNew(ledger, SAMPLE) ? 0 : 1;

  if (added) saveLedger(ledger);

  writeReport(added ? 1 : 0, added ? 0 : 1, added);

  execSync("npm run validate-ledger", { cwd: ROOT, stdio: "inherit" });

  const after = loadLedger().items.length;
  console.log(`Smoke test OK:`);
  console.log(`  - Ledger: ${before} -> ${after} items`);
  console.log(`  - First append: ${added ? "added" : "skipped (already exists)"}`);
  console.log(`  - Dedup skip: ${added ? "N/A" : "confirmed duplicate blocked"}`);
  console.log(`  - Report: ${REPORT_PATH}`);
}

main();
